ASI.Basecode.WebApp/Controllers/KnowledgeBaseController.cs
using ASI.Basecode.Services.Interfaces;
using ASI.Basecode.Services.ServiceModels;
using ASI.Basecode.WebApp.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;

namespace ASI.Basecode.WebApp.Controllers
{
    /// <summary>
    /// Sample Crud Controller
    /// </summary>
    public class KnowledgeBaseController : ControllerBase<KnowledgeBaseController>
    {
        private readonly IKnowledgeBaseService _knowledgeBaseService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="httpContextAccessor"></param>
        /// <param name="loggerFactory"></param>
        /// <param name="configuration"></param>
        /// <param name="localizer"></param>
        /// <param name="mapper"></param>
        public KnowledgeBaseController(IKnowledgeBaseService knowledgeBaseService,
                                IHttpContextAccessor httpContextAccessor,
                                ILoggerFactory loggerFactory,
                                IConfiguration configuration,
                                IUserPreferencesService userPreferences,
                                IMapper mapper = null) : base(httpContextAccessor, loggerFactory, configuration, mapper, userPreferences)
        {
            _knowledgeBaseService = knowledgeBaseService;
        }

        #region GET Functions

        /// <summary>
        /// Returns Sample Crud View.
        /// </summary>
        /// <returns> Sample Crud View </returns>
        [HttpGet]
        [Authorize]
        public IActionResult Index(string searchTerm, string selectedCategories = "All", string sortBy = "CreatedDate", string sortOrder = "asc", int pageNumber = 1, bool clearFilters = false)
        {
            if (clearFilters)
            {
                selectedCategories = "All";
                sortBy = "CreatedDate";
                sortOrder = "asc";
                searchTerm = string.Empty;
            }

            var pageSize = 5;

            var totalArticlesCount = _knowledgeBaseService.CountArticles(searchTerm, selectedCategories);
            var articles = _knowledgeBaseService.SearchArticles(searchTerm, selectedCategories, sortBy, sortOrder, pageNumber, pageSize);

            var viewModel = new PaginatedList<KnowledgeBaseViewModel>(articles, totalArticlesCount, pageNumber, pageSize);

            ViewBag.Categories = _knowledgeBaseService.GetArticleCategories();
            ViewBag.SortBy = sortBy;
            ViewBag.SortOrder = sortOrder;
            ViewBag.SearchTerm = searchTerm;
            ViewBag.SelectedCategories = selectedCategories;

            return View(viewModel);
        }

        /// <summary>
        /// Return Create View
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Policy = "AdminOrAgent")]
        public IActionResult Create()
        {
            var model = new KnowledgeBaseViewModel
            {
                ArticleCategories = _knowledgeBaseService.GetArticleCategories()
            };
            return View(model);
        }

        /// <summary>Returns Details View</summary>
        /// <param name="articleId">The article identifier.</param>
        /// <returns>
        ///   <br />
        /// </returns>
        [HttpGet]
        [Authorize]
        public IActionResult Details(string articleId)
        {
            var article = _knowledgeBaseService.GetArticleById(articleId);
            if (article == null)
            {
                return RedirectToAction("Index");
            }
            return View(article);
        }

        /// <summary>Returns the Edit View</summary>
        /// <param name="articleId">The article identifier.</param>
        /// <returns>
        ///   <br />
        /// </returns>
        [HttpGet]
        [Authorize(Policy = "AdminOrAgent")]
        public IActionResult Edit(string articleId)
        {
            var article = _knowledgeBaseService.GetArticleById(articleId);
            article.ArticleCategories = _knowledgeBaseService.GetArticleCategories();
            return PartialView("_EditArticleModal", article);
        }

        /// <summary>Returns the Delete View</summary>
        /// <param name="articleId">The article identifier.</param>
        /// <returns>
        ///   <br />
        /// </returns>
        [HttpGet]
        [Authorize(Policy = "Admin")]
        public IActionResult Delete(string articleId)
        {
            var data = _knowledgeBaseService.GetArticleById(articleId);
            return View(data);
        }
        #endregion

        #region POST Functions
        /// <summary>Posts the create.</summary>
        /// <param name="model">The model.</param>
        /// <returns>
        ///   <br />
        /// </returns>
        [HttpPost]
        [Authorize]
        public IActionResult PostCreate(KnowledgeBaseViewModel model)
        {
            model.AuthorId = _session.GetString("UserId");
            _knowledgeBaseService.Add(model);
            TempData["CreateMessage"] = "Article Added Succesfully";
            return RedirectToAction("Index");
        }

        /// <summary>Posts the update.</summary>
        /// <param name="model">The model.</param>
        /// <returns>
        ///   <br />
        /// </returns>
        [HttpPost]
        [Authorize]
        public IActionResult PostUpdate(KnowledgeBaseViewModel model)
        {
            _knowledgeBaseService.Update(model);
            TempData["UpdateMessage"] = "Article Updated Succesfully";
            return RedirectToAction("Index");
        }

        /// <summary>Posts the delete.</summary>
        /// <param name="articleId">The article identifier.</param>
        /// <returns>
        ///   <br />
        /// </returns>
        [HttpPost]
        [Authorize(Policy = "Admin")]
        public IActionResult PostDelete(string articleId)
        {
            _knowledgeBaseService.Delete(articleId);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

ASI.Basecode.WebApp/Controllers/NotificationController.cs
using ASI.Basecode.Data.Interfaces;
using ASI.Basecode.Services.Interfaces;
using ASI.Basecode.Services.Services;
using ASI.Basecode.WebApp.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Security.Claims;

namespace ASI.Basecode.WebApp.Controllers
{
    public class NotificationController : ControllerBase<NotificationController>
    {
        private readonly INotificationService _notificationService;
        private readonly INotificationRepository _notificationRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public NotificationController(INotificationService notificationService,
                                      IHttpContextAccessor httpContextAccessor,
                                      ILoggerFactory loggerFactory,
                                      IConfiguration configuration,
                                      INotificationRepository notificationRepository,
                                      IUserPreferencesService userPreferences,
                                      IMapper mapper = null) : base(httpContextAccessor, loggerFactory, configuration, mapper, userPreferences)
        {
            _notificationService = notificationService;
            _httpContextAccessor = httpContextAccessor;
            _notificationRepository = notificationRepository;
        }

        public IActionResult Index()
        {

            var userId = _httpContextAccessor.HttpContext.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var notifications = _notificationService.RetrieveAll(userId).OrderByDescending(x => x.NotificationDate);

            return PartialView("_NotificationModal", notifications);
        }

        public IActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            var notification = _notificationRepository.FindById(id);
            if (notification == null)
            {
                return NotFound();
            }

            _notificationRepository.Delete(notification.NotificationId);

            return Ok();
        }
        #region Mark As Read

        /// <summary>
        /// Marks as read.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAsRead(string id)
        {
            _notificationService.MarkNotificationAsRead(id);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Marks all as read.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAllAsRead()
        {
            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            _notificationService.MarkAllNotificationsAsRead(userId);
            return RedirectToAction("Index");
        }
        #endregion

        #region Mark As Unread
        /// <summary>
        /// Marks as unread.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAsUnread(string id)
        {
            _notificationService.MarkNotificationAsUnread(id);
            return RedirectToAction("Index");
        }
      
        /// <summary>
        /// Marks all as unread.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAllAsUnread()
        {
            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            _notificationService.MarkAllNotificationsAsUnread(userId);
            return RedirectToAction("Index");
        }

        #endregion  
    }
}

ASI.Basecode.WebApp/Views/KnowledgeBase/Index.cshtml
@model ASI.Basecode.Services.ServiceModels.PaginatedList<ASI.Basecode.Services.ServiceModels.KnowledgeBaseViewModel>
@using ASI.Basecode.Data.Models

@{
    ViewData["Title"] = "Articles";
    await Html.RenderPartialAsync("_CreateArticleModal", new ASI.Basecode.Services.ServiceModels.KnowledgeBaseViewModel
            {
                ArticleCategories = ViewBag.Categories
            });

    string selectedCategories = ViewData["SelectedCategories"] as string;
    string sortBy = ViewData["SortBy"] as string;
    string sortOrder = ViewData["SortOrder"] as string;
    string searchTerm = ViewBag.SearchTerm as string;
    int pageIndex = Model.PageIndex;
    int pageSize = (ViewData["PageSize"] as int?) ?? 5;
}

<div class="d-flex justify-content-between nav-header">
    <h1 class="display-6">Articles</h1>
    <div class="d-flex justify-content-between">
        <form method="get" asp-action="Index">
            <div class="form-group input-group">
                <input type="text" name="searchTerm" class="form-control btn-radius px-3" placeholder="Search Articles..." value="@searchTerm" />
                <span class="input-group-append">
                    <button type="submit" class="btn btn-primary btn-radius-r px-3">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        @if (User.IsInRole("Admin") || User.IsInRole("Support Agent"))
        {
            <div class="mx-3">
                <button type="button" class="btn btn-primary btn-radius px-3" data-toggle="modal" data-target="#createModal">
                    <i class="fa fa-plus"></i>
                    New Article
                </button>
            </div>
        }
        <div class="mr-3">
            <button type="button" class="btn notif-bell" id="notifBellBtn">
                <i class="fa fa-bell px-1"></i>
            </button>
        </div>
        <div id="notificationModal" class="modal fixed-right fade" tabindex="-2" role="dialog">
            <div class="modal-dialog modal-dialog-aside" role="document">
                <div class="modal-content">
                    <!-- Notification Modal -->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid px-4 py-3">
    <div class="row">
        <div class="col-9">
            @if (!Model.Any())
            {
                <div class="alert alert-warning text-center" role="alert">
                    @(!selectedCategories.Any() ? Html.Raw("No articles found") : Html.Raw("No articles found matching the criteria"))
                </div>
            }
            else
            {
                <div class="container py-3">
                    @foreach (var item in Model)
                    {
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-start">
                                    <div style="display: flex; align-items: center;">
                                        <h5 class="card-title m-0 pr-2 poppins-semi-bold">@Html.DisplayFor(modelItem => item.Title)</h5>
                                        <small class="text-muted pt-1">(@Html.DisplayFor(modelItem => item.Category.CategoryName))</small>
                                    </div>
                                    <small class="text-muted">@Html.DisplayFor(modelItem => item.CreatedDate)</small>
                                </div>
                                <p class="card-text mt-3">@Html.DisplayFor(modelItem => item.Content)</p>
                                <div class="d-flex justify-content-between align-items-end mt-4">
                                    <div>
                                        <h6 class="card-subtitle text-muted">@Html.DisplayFor(modelItem => item.Author.Name)</h6>
                                    </div>
                                    <div>
                                        @if (User.IsInRole("Admin") || User.IsInRole("Support Agent"))
                                        {
                                            <a href="javascript:void(0);" class="fas fas fa-pencil action-icon" data-toggle="modal" data-target="#editArticleModal" data-articleid="@item.ArticleId" data-toggle="tooltip" title="Edit"></a>
                                        }
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a href="javascript:void(0);" onclick="displayDeleteModal('@item.ArticleId')" class="fas fa-trash action-icon ms-2"></a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }

            <nav class="container">
                <ul class="pagination">
                    @if (Model.HasPreviousPage)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="Index"
                                asp-route-sortBy="@sortBy"
                                asp-route-sortOrder="@sortOrder"
                                asp-route-searchTerm="@searchTerm"
                                asp-route-selectedCategories="@selectedCategories"
                                asp-route-pageIndex="@(pageIndex - 1)">Previous</a>
                        </li>
                    }
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == pageIndex ? "active" : "")">
                            <a class="page-link" asp-action="Index"
                                asp-route-sortBy="@sortBy"
                                asp-route-sortOrder="@sortOrder"
                                asp-route-searchTerm="@searchTerm"
                                asp-route-selectedCategories="@selectedCategories"
                                asp-route-pageIndex="@i">@i</a>
                        </li>
                    }
                    @if (Model.HasNextPage)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="Index"
                                asp-route-sortBy="@sortBy"
                                asp-route-sortOrder="@sortOrder"
                                asp-route-searchTerm="@searchTerm"
                                asp-route-selectedCategories="@selectedCategories"
                                asp-route-pageIndex="@(pageIndex + 1)">Next</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>

        @* Filters and Sorting Card *@
        @await Html.PartialAsync("_FiltersAndSortCardArticles")
    </div>
</div>

@* Delete Article Modal *@
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDeleteBtn">Delete</button>
            </div>
        </div>

    </div>
</div>

@* Edit Article Modal *@
<div class="modal fade" id="editArticleModal" tabindex="-1" role="dialog" aria-labelledby="editArticleModallLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content modal-content-article" id="editArticleModalContent">
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/knowledgebase.js"></script>
    <script>
        var createMessage = '@TempData["CreateMessage"]';
        var deleteMessage = sessionStorage.getItem("DeleteSuccess");
        var updateMessage = '@TempData["UpdateMessage"]';
        if (createMessage) {
            toastr.success(createMessage);
        } else if (deleteMessage) {
            toastr.success(deleteMessage);
            sessionStorage.removeItem("DeleteSuccess");
        } else if (updateMessage) {
            toastr.success(updateMessage);
        }
        $(document).ready(function () {
            $('#categories').multiselect({
                includeSelectAllOption: true,
                nonSelectedText: 'Select Categories'
            });
        });

        function displayDeleteModal(id) {
            itemId = id;
            $('#deleteModal').modal('show');
        }
        $('#confirmDeleteBtn').on('click', function () {
            $.ajax({
                url: '@Url.Action("PostDelete", "KnowledgeBase")',
                type: 'POST',
                data: { articleId: itemId },
                success: function (result) {
                    sessionStorage.setItem("DeleteSuccess", "Deleted Successfully");
                    window.location.href = '@Url.Action("Index", "KnowledgeBase")';
                }
            })
        })
        $(document).ready(function () {
            $('.fa-pencil').click(function () {
                var articleId = $(this).data('articleid');
                var url = '@Url.Action("Edit")?articleId=' + articleId;
                $.get(url, function (data) {
                    $('#editArticleModalContent').html(data);
                    setupEditModal();
                });
            });
        });
    </script>


    <script>
        $(document).ready(function () {
            $('#notifBellBtn').click(function () {
                $.ajax({
                    url: '@Url.Action("Index", "Notification")',
                    success: function (result) {
                        $('#notificationModal .modal-content').html(result);
                        $('#notificationModal').modal('show');
                    }
                });
            });
        });
    </script>
}

@section styles {
    <link rel="stylesheet" href="~/css/notification.css" />
    <link rel="stylesheet" href="~/css/pagination.css" />
}

ASI.Basecode.WebApp/Views/KnowledgeBase/_CreateArticleModal.cshtml
@model ASI.Basecode.Services.ServiceModels.KnowledgeBaseViewModel

@{
    ViewData["Title"] = "Create";
}
@section styles {
    <link rel="stylesheet" href="~/css/articles.css" />
}

<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Create New Article</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="PostCreate" id="CreateArticleForm" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <select asp-for="CategoryId" class="form-control">
                            @foreach (var item in Model.ArticleCategories)
                            {
                                <option value="@item.CategoryId">@item.CategoryName</option>
                            }
                        </select>
                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Title" for="title">Title</label>
                            <input asp-for="Title" type="text" id="title" name="title" class="form-control" maxlength="100" />
                            <small id="remainingTitleChars" class="form-text text-muted ml-2">100 characters remaining</small>
                            <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Content" for="content">Content</label>
                        <textarea asp-for="Content" id="content" name="content" class="form-control" maxlength="800"></textarea>
                        <small id="remainingContentChars" class="form-text text-muted">800 characters remaining</small>
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="AuthorId" type="hidden" />
                    </div>
                    <div class="form-group d-flex justify-content-center my-3">
                        <input type="submit" value="Create" class="btn btn-white btn-radius" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ASI.Basecode.WebApp/Views/KnowledgeBase/_EditArticleModal.cshtml
@model ASI.Basecode.Services.ServiceModels.KnowledgeBaseViewModel

@{
    ViewData["Title"] = "_EditArticleModal";
}
@section styles {
    <link rel="stylesheet" href="~/css/articles.css" />
}

<div class="modal-header">
    <h5 class="modal-title" id="editModalLabel">Edit Article</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form asp-action="PostUpdate" id="EditArticleForm" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Category" class="control-label"></label>
            <select asp-for="CategoryId" class="form-control">
                @foreach (var item in Model.ArticleCategories)
                {
                    <option value="@item.CategoryId">@item.CategoryName</option>
                } 
            </select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" id="editTitle" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
            <span id="editRemainingTitleChars" class="text-muted">100 characters remaining</span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" id="editContent" class="form-control"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
            <span id="editRemainingContentChars" class="text-muted">800 characters remaining</span>
        </div>
        <div class="form-group">
            <input asp-for="AuthorId" type="hidden" />
        </div>
        <div class="form-group d-flex justify-content-center my-3">
            <input type="submit" value="Update" class="btn btn-white btn-radius" />
        </div>
        <input asp-for="ArticleId" type="hidden" />
    </form>
</div>

<script src="~/js/knowledgebase.js"></script>

ASI.Basecode.WebApp/Views/KnowledgeBase/_FiltersAndSortCardArticles.cshtml
@model ASI.Basecode.Services.ServiceModels.PaginatedList<ASI.Basecode.Services.ServiceModels.KnowledgeBaseViewModel>
@using ASI.Basecode.Data.Models

@{
    string selectedCategories = ViewData["SelectedCategories"] as string;
    string sortBy = ViewData["SortBy"] as string;
    string sortOrder = ViewData["SortOrder"] as string;
    string searchTerm = ViewData["SearchTerm"] as string;
    var categories = ViewBag.Categories as IEnumerable<ArticleCategory>;
}

<div class="col-3">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title mb-0">Article Filters & Sort</h5>
        </div>
        <div class="card-body">
            <form method="get" asp-action="Index">
                <div class="mb-3">
                    <label for="selectedCategories">Categories: </label>
                    <select id="selectedCategories" name="selectedCategories" class="form-control">
                        <option value="All">All</option>
                        @foreach (var category in categories)
                        {
                            <option value="@category.CategoryId" selected="@(selectedCategories == category.CategoryId ? "selected" : null)">@category.CategoryName</option>
                        }
                    </select>
                </div>
                <hr />
                <div class="mb-3">
                    <label for="sortBy">Sort By:</label>
                    <select asp-for="@sortBy" id="sortBy" name="sortBy" class="form-control">
                        <option value="CreatedDate" selected="@(sortBy == "CreatedDate")">Created Date</option>
                        <option value="UpdatedDate" selected="@(sortBy == "UpdatedDate")">Updated Date</option>
                        <option value="Title" selected="@(sortBy == "Title")">Title</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="sortOrder">Sort Order:</label>
                    <select asp-for="@sortOrder" id="sortOrder" name="sortOrder" class="form-control">
                        <option value="asc" selected="@(sortOrder == "asc")">Ascending</option>
                        <option value="desc" selected="@(sortOrder == "desc")">Descending</option>
                    </select>
                </div>
                <hr />
                <button type="submit" class="btn btn-primary w-100">Apply</button>
                <input type="hidden" name="searchTerm" value="@searchTerm" />
                <input type="hidden" name="clearFilters" id="clearFilters" value="false" />
            </form>
            @if (!selectedCategories.Equals("All") || !sortBy.Equals("CreatedDate") || !sortOrder.Equals("asc"))
            {
                <hr />
                <form>
                    <a href="@Url.Action("Index", "KnowledgeBase", new { clearFilters = true, searchTerm = @searchTerm })" class="btn btn-secondary w-100 text-black">Clear</a>
                </form>
                <hr />
            }
        </div>
    </div>
</div>