ASI.Basecode.WebApp/Controllers/NotificationController.cs
using ASI.Basecode.Data.Interfaces;
using ASI.Basecode.Services.Interfaces;
using ASI.Basecode.Services.Services;
using ASI.Basecode.WebApp.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Security.Claims;

namespace ASI.Basecode.WebApp.Controllers
{
    public class NotificationController : ControllerBase<NotificationController>
    {
        private readonly INotificationService _notificationService;
        private readonly INotificationRepository _notificationRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public NotificationController(INotificationService notificationService,
                                      IHttpContextAccessor httpContextAccessor,
                                      ILoggerFactory loggerFactory,
                                      IConfiguration configuration,
                                      INotificationRepository notificationRepository,
                                      IUserPreferencesService userPreferences,
                                      IMapper mapper = null) : base(httpContextAccessor, loggerFactory, configuration, mapper, userPreferences)
        {
            _notificationService = notificationService;
            _httpContextAccessor = httpContextAccessor;
            _notificationRepository = notificationRepository;
        }

        public IActionResult Index()
        {

            var userId = _httpContextAccessor.HttpContext.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var notifications = _notificationService.RetrieveAll(userId).OrderByDescending(x => x.NotificationDate);

            return PartialView("_NotificationModal", notifications);
        }

        public IActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            var notification = _notificationRepository.FindById(id);
            if (notification == null)
            {
                return NotFound();
            }

            _notificationRepository.Delete(notification.NotificationId);

            return Ok();
        }
        #region Mark As Read

        /// <summary>
        /// Marks as read.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAsRead(string id)
        {
            _notificationService.MarkNotificationAsRead(id);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Marks all as read.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAllAsRead()
        {
            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            _notificationService.MarkAllNotificationsAsRead(userId);
            return RedirectToAction("Index");
        }
        #endregion

        #region Mark As Unread
        /// <summary>
        /// Marks as unread.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAsUnread(string id)
        {
            _notificationService.MarkNotificationAsUnread(id);
            return RedirectToAction("Index");
        }
      
        /// <summary>
        /// Marks all as unread.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult MarkAllAsUnread()
        {
            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            _notificationService.MarkAllNotificationsAsUnread(userId);
            return RedirectToAction("Index");
        }

        #endregion  
    }
}

ASI.Basecode.WebApp/Controllers/TeamController.cs
using ASI.Basecode.Data.Models;
using ASI.Basecode.Services.Interfaces;
using ASI.Basecode.Services.ServiceModels;
using ASI.Basecode.WebApp.Authentication;
using ASI.Basecode.WebApp.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;
using ASI.Basecode.Resources.Messages;

namespace ASI.Basecode.WebApp.Controllers
{
    /// <summary>
    /// Controller for handling team-related operations.
    /// </summary>
    [Route("team")]
    public class TeamController : ControllerBase<TeamController>
    {
        private readonly ITeamService _teamService;
        private readonly ITicketService _ticketService;

        /// <summary>
        /// Initializes a new instance of the <see cref="TeamController"/> class.
        /// </summary>
        /// <param name="httpContextAccessor">The HTTP context accessor.</param>
        /// <param name="loggerFactory">The logger factory.</param>
        /// <param name="configuration">The configuration.</param>
        /// <param name="mapper">The mapper.</param>
        /// <param name="teamService">The team service.</param>
        /// <param name="ticketService">The ticket service.</param>
        /// <param name="userPreferences">The user preferences service.</param>
        /// <param name="tokenValidationParametersFactory">The token validation parameters factory.</param>
        /// <param name="tokenProviderOptionsFactory">The token provider options factory.</param>
        public TeamController(
            IHttpContextAccessor httpContextAccessor,
            ILoggerFactory loggerFactory,
            IConfiguration configuration,
            IMapper mapper,
            ITeamService teamService,
            ITicketService ticketService,
            IUserPreferencesService userPreferences,
            TokenValidationParametersFactory tokenValidationParametersFactory,
            TokenProviderOptionsFactory tokenProviderOptionsFactory) : base(httpContextAccessor, loggerFactory, configuration, mapper, userPreferences)
        {
            this._teamService = teamService;
            this._ticketService = ticketService;
        }

        #region GET Methods 
        /// <summary>
        /// Show all teams.
        /// </summary>
        /// <param name="sortBy">The sort by option.</param>
        /// <param name="filterBy">The filter by option.</param>
        /// <param name="specialization">The specialization filter.</param>
        /// <param name="pageIndex">The page index.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [Authorize(Policy = "Admin")]
        [HttpGet]
        [Route("all")]
        public async Task<IActionResult> GetAll(string sortBy, string filterBy, string specialization, int pageIndex = 1)
        {
            return await HandleExceptionAsync(async () =>
            {
                var teams = await _teamService.GetAllAsync(sortBy, filterBy, specialization, pageIndex, 5);

                ViewData["FilterBy"] = filterBy;
                ViewData["SortBy"] = sortBy;
                ViewData["Specialization"] = specialization;
                ViewBag.CTs = (await _ticketService.GetCategoryTypesAsync())
                                .Where(ct => !ct.CategoryName.Contains("Other"))
                                .OrderBy(ct => ct.CategoryName).ToList();

                return View("ViewAll", teams);
            }, "GetAll");
        }

        /// <summary>
        /// Views the selected team.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="showModal">The show modal.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [HttpGet]
        [Authorize(Policy = "Admin")]
        [Route("view")]
        public async Task<IActionResult> ViewTeam(string id, string showModal = null)
        {
            return await HandleExceptionAsync(async () =>
            {
                if (string.IsNullOrEmpty(id))
                {
                    TempData["ErrorMessage"] = Errors.InvalidTeamId;
                    return RedirectToAction("GetAll");
                }

                var team = await _teamService.GetTeamByIdAsync(id);
                if (team == null)
                {
                    TempData["ErrorMessage"] = Errors.TeamNotFound;
                    return RedirectToAction("GetAll");
                }
                var agents = await _teamService.GetAgentsAsync();
                var teams = await _teamService.GetAllStrippedAsync();

                ViewBag.ShowModal = showModal;
                ViewBag.AssignedAgents = agents.Where(x => x.TeamMember?.TeamId == id).ToList();
                ViewBag.UnassignedAgents = agents.Where(x => x.TeamMember == null).ToList();
                ViewBag.Teams = teams.Where(x => x.TeamId != id).ToList();
                ViewBag.CTs = (await _ticketService.GetCategoryTypesAsync())
                                .Where(ct => !ct.CategoryName.Contains("Other"))
                                .OrderBy(ct => ct.CategoryName).ToList();

                return View("ViewTeam", team);
            }, "ViewTeam");
        }
        #endregion GET Methods

        #region POST Methods        
        /// <summary>
        /// Creates a new team.
        /// </summary>
        /// <param name="model">The team view model.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [HttpPost]
        [Authorize(Policy = "Admin")]
        [Route("create")]
        public async Task<IActionResult> Create(TeamViewModel model)
        {
            return await HandleExceptionAsync(async () =>
            {
                if (ModelState.IsValid)
                {
                    await _teamService.AddAsync(model);
                    TempData["SuccessMessage"] = Common.SuccessCreateTeam;
                    return Json(new { success = true });
                }
                TempData["ErrorMessage"] = Errors.ErrorCreateTeam;
                return Json(new { success = false });
            }, "Create");
        }

        /// <summary>
        /// Updates the selected team.
        /// </summary>
        /// <param name="model">The team view model.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [HttpPost]
        [Authorize(Policy = "Admin")]
        [Route("update")]
        public async Task<IActionResult> Update(TeamViewModel model)
        {
            return await HandleExceptionAsync(async () =>
            {
                if (ModelState.IsValid)
                {
                    await _teamService.UpdateAsync(model);
                    TempData["SuccessMessage"] = Common.SuccessUpdateTeam;
                    return Json(new { success = true });
                }
                TempData["ErrorMessage"] = Errors.ErrorUpdateTeam;
                return Json(new { success = false });
            }, "Update");
        }

        /// <summary>
        /// Deletes the selected team.
        /// </summary>
        /// <param name="id">The team identifier.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [HttpPost]
        [Authorize(Policy = "Admin")]
        [Route("delete")]
        public async Task<IActionResult> Delete(string id)
        {
            return await HandleExceptionAsync(async () =>
            {
                if (ModelState.IsValid)
                {
                    await _teamService.DeleteAsync(id);
                    TempData["SuccessMessage"] = Common.SuccessDeleteTeam;
                    return Json(new { success = true });
                }
                TempData["ErrorMessage"] = Errors.ErrorDeleteTeam;
                return Json(new { success = false });
            }, "Delete");
        }

        /// <summary>
        /// Assigns an agent to a team.
        /// </summary>
        /// <param name="teamId">The team identifier.</param>
        /// <param name="agentId">The agent identifier.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [HttpPost]
        [Authorize(Policy = "Admin")]
        [Route("assignagent")]
        public async Task<IActionResult> AssignAgent(string teamId, string agentId)
        {
            return await HandleExceptionAsync(async () =>
            {
                if (ModelState.IsValid)
                {
                    await _teamService.AddTeamMemberAsync(teamId, agentId);
                    TempData["SuccessMessage"] = Common.SuccessAssignAgent;
                    return Json(new { success = true });
                }
                TempData["ErrorMessage"] = Errors.ErrorAssignAgent;
                return Json(new { success = false });
            }, "AssignAgent");
        }

        /// <summary>
        /// Reassigns an agent to a different team.
        /// </summary>
        /// <param name="oldTeamId">The old team identifier.</param>
        /// <param name="newTeamId">The new team identifier.</param>
        /// <param name="agentId">The agent identifier.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="IActionResult"/>.</returns>
        [HttpPost]
        [Authorize(Policy = "Admin")]
        [Route("reassignagent")]

ASI.Basecode.WebApp/Views/Team/ViewAll.cshtml
@model ASI.Basecode.Services.ServiceModels.PaginatedList<ASI.Basecode.Services.ServiceModels.TeamViewModel>
@using Humanizer

@{
    ViewData["Title"] = "All Teams";
    await Html.RenderPartialAsync("_CreateTeamModal", new ASI.Basecode.Services.ServiceModels.TeamViewModel());
    await Html.RenderPartialAsync("_DeleteModal");

    string filterBy = ViewData["FilterBy"] as string;
    string sortBy = ViewData["SortBy"] as string;
    string specialization = ViewData["Specialization"] as string;
    int pageIndex = Model.PageIndex;

    string sortByName = string.IsNullOrEmpty(sortBy) ? "name_desc" : null;
    string sortBySpecialization = sortBy == "specialization" ? "specialization_desc" : "specialization";
    string sortByNoOfAgents = sortBy == "agents" ? "agents_desc" : "agents";
    string sortByActiveTickets = sortBy == "active" ? "active_desc" : "active";
    string sortByInactiveTickets = sortBy == "inactive" ? "inactive_desc" : "inactive";
    string sortByAvgCompletionTime = sortBy == "completion" ? "completion_desc" : "completion";
    string sortByAvgFeedbackRating = sortBy == "rating" ? "rating_desc" : "rating";
}

@section styles {
    <link rel="stylesheet" href="~/css/team.css" />
    <link rel="stylesheet" href="~/css/pagination.css" />
    <link rel="stylesheet" href="~/css/notification.css" />
}

<div class="d-flex justify-content-between nav-header">
    <h1 class="display-6">Team Management</h1>
    <div class="d-flex justify-content-between">
        <form method="get" asp-action="GetAll" asp-route-sortBy="@sortBy" asp-route-filterBy="@filterBy">
            <div class="form-group input-group">
                <input type="text" name="filterBy" class="form-control btn-radius px-3" placeholder="Name or specialization" value="@filterBy" />
                <span class="input-group-append">
                    <button type="submit" class="btn btn-primary btn-radius-r px-3">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
            <input type="hidden" name="sortBy" value="@sortBy" />
        </form>
        <div class="mx-3">
            <p>
                @if (User.IsInRole("Admin"))
                {
                    <button type="button" class="btn btn-primary btn-radius px-3" data-toggle="modal" data-target="#createTeamModal">
                        <i class="fa fa-plus"></i>
                        New Team
                    </button>
                }
            </p>
        </div>
        <div class="mr-3">
            <button type="button" class="btn notif-bell" id="notifBellBtn">
                <i class="fa fa-bell px-1"></i>
            </button>
        </div>
        <div id="notificationModal" class="modal fixed-right fade" tabindex="-2" role="dialog">
            <div class="modal-dialog modal-dialog-aside" role="document">
                <div class="modal-content">
                    <!-- Notification Modal -->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid px-4 py-3">
    <table class="table table-white">
        <thead>
            <tr>
                <th>
                    <a asp-action="GetAll" asp-route-sortBy="@sortByName" asp-route-filterBy="@filterBy" asp-route-pageIndex="@pageIndex" asp-route-specialization="@specialization" class="text-black">
                        @Html.DisplayNameFor(model => model.First().Name)
                        @(string.IsNullOrEmpty(sortBy) ? Html.Raw("<i class='fa-solid fa-sort-up'></i>") : (sortBy == "name_desc" ? Html.Raw("<i class='fa-solid fa-sort-down'></i>") : Html.Raw("<i class='fa-solid fa-sort'></i>")))
                    </a>
                </th>
                <th>
                    <div class="dropdown">
                        <a class="text-black" href="#" id="roleDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Html.DisplayNameFor(model => model.First().Specialization)
                            <i class="fa-solid fa-chevron-down"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="specializationDropdown">
                            <a class="dropdown-item" asp-action="GetAll" asp-route-sortBy="@sortBy" asp-route-filterBy="@filterBy" asp-route-specialization="">All</a>
                            @foreach (var ct in ViewBag.CTs)
                            {
                                <a class="dropdown-item" asp-action="GetAll" asp-route-sortBy="@sortBy" asp-route-filterBy="@filterBy" asp-route-specialization="@ct.CategoryTypeId">@ct.CategoryName</a>
                            }
                        </div>
                    </div>
                </th>
                <th>
                    <a asp-action="GetAll" asp-route-sortBy="@sortByNoOfAgents" asp-route-filterBy="@filterBy" asp-route-pageIndex="@pageIndex" asp-route-specialization="@specialization" class="text-black">
                        @Html.DisplayNameFor(model => model.First().NumberOfAgents)
                        @(sortBy == "agents" ? Html.Raw("<i class='fa-solid fa-sort-up'></i>") : (sortBy == "agents_desc" ? Html.Raw("<i class='fa-solid fa-sort-down'></i>") : Html.Raw("<i class='fa-solid fa-sort'></i>")))
                    </a>
                </th>
                <th>
                    <a asp-action="GetAll" asp-route-sortBy="@sortByActiveTickets" asp-route-filterBy="@filterBy" asp-route-pageIndex="@pageIndex" asp-route-specialization="@specialization" class="text-black">
                        @Html.DisplayNameFor(model => model.First().ActiveTicketsCount)
                        @(sortBy == "active" ? Html.Raw("<i class='fa-solid fa-sort-up'></i>") : (sortBy == "active_desc" ? Html.Raw("<i class='fa-solid fa-sort-down'></i>") : Html.Raw("<i class='fa-solid fa-sort'></i>")))
                    </a>
                </th>
                <th>
                    <a asp-action="GetAll" asp-route-sortBy="@sortByInactiveTickets" asp-route-filterBy="@filterBy" asp-route-pageIndex="@pageIndex" asp-route-specialization="@specialization" class="text-black">
                        @Html.DisplayNameFor(model => model.First().CompletedTicketsCount)
                        @(sortBy == "inactive" ? Html.Raw("<i class='fa-solid fa-sort-up'></i>") : (sortBy == "inactive_desc" ? Html.Raw("<i class='fa-solid fa-sort-down'></i>") : Html.Raw("<i class='fa-solid fa-sort'></i>")))
                    </a>
                </th>
                <th>
                    <a asp-action="GetAll" asp-route-sortBy="@sortByAvgCompletionTime" asp-route-filterBy="@filterBy" asp-route-pageIndex="@pageIndex" asp-route-specialization="@specialization" class="text-black">
                        @Html.DisplayNameFor(model => model.First().AverageResolutionTime)
                        @(sortBy == "completion" ? Html.Raw("<i class='fa-solid fa-sort-up'></i>") : (sortBy == "completion_desc" ? Html.Raw("<i class='fa-solid fa-sort-down'></i>") : Html.Raw("<i class='fa-solid fa-sort'></i>")))
                    </a>
                </th>
                <th>
                    <a asp-action="GetAll" asp-route-sortBy="@sortByAvgFeedbackRating" asp-route-filterBy="@filterBy" asp-route-pageIndex="@pageIndex" asp-route-specialization="@specialization" class="text-black">
                        @Html.DisplayNameFor(model => model.First().AverageFeedbackRating)
                        @(sortBy == "rating" ? Html.Raw("<i class='fa-solid fa-sort-up'></i>") : (sortBy == "rating_desc" ? Html.Raw("<i class='fa-solid fa-sort-down'></i>") : Html.Raw("<i class='fa-solid fa-sort'></i>")))
                    </a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (!Model.Any())
            {
                <tr>
                    <td colspan="13" class="alert alert-warning text-center" role="alert">
                        @(string.IsNullOrEmpty(filterBy) ? Html.Raw("No teams found") : Html.Raw("No teams found matching the criteria"))
                    </td>
                </tr>
            }
            else
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Specialization.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberOfAgents)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ActiveTicketsCount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompletedTicketsCount)
                        </td>
                        <td>
                            @{
                                var averageResolutionTime = TimeSpan.FromMinutes(Convert.ToDouble(item.AverageResolutionTime));
                            }
                            @averageResolutionTime.Humanize(2, maxUnit: Humanizer.Localisation.TimeUnit.Day)
                        </td>
                        <td>
                            @{
                                double rating;
                                if (double.TryParse(item.AverageFeedbackRating, out rating))
                                {
                                    @rating.ToString("F1")
                                }
                                else
                                {
                                    @item.AverageFeedbackRating
                                }
                            }
                        </td>
                        <td>
                            @Html.ActionLink("", "ViewTeam", new { id = item.TeamId, showModal = "editTeam" }, new { @class = "fas fa-edit action-icon" }) |
                            @Html.ActionLink("", "ViewTeam", new { id = item.TeamId, sortBy = sortBy, filterBy = filterBy, specialization = specialization, pageIndex = Model.PageIndex }, new { @class = "fas fa-info-circle action-icon" }) |
                            <a href="javascript:void(0);" onclick="displayDeleteModal('@item.TeamId')" class="fas fa-trash-alt action-icon"></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <nav>
        <ul class="pagination">
            @if (Model.HasPreviousPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="GetAll" asp-route-pageIndex="@(Model.PageIndex - 1)" asp-route-sortBy="@sortBy" asp-route-filterBy="@filterBy">Previous</a>
                </li>
            }
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                    <a class="page-link" asp-action="GetAll" asp-route-pageIndex="@i" asp-route-sortBy="@sortBy" asp-route-filterBy="@filterBy">@i</a>
                </li>
            }
            @if (Model.HasNextPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="GetAll" asp-route-pageIndex="@(Model.PageIndex + 1)" asp-route-sortBy="@sortBy" asp-route-filterBy="@filterBy">Next</a>
                </li>
            }
        </ul>
    </nav>
</div>

@*---- Values passed to the js files ----*@
<div id="tempDataContainer" data-success="@TempData["SuccessMessage"]" data-error="@TempData["ErrorMessage"]"></div>
<input type="hidden" id="baseUrl" value="@Url.Action("GetAll", "Team")" />
<input type="hidden" id="deleteUrl" value="@Url.Action("Delete", "Team")" />

@section Scripts {
    <script src="~/js/delete.js"></script>
    <script src="~/js/toastrNotification.js"></script>
    <script src="~/js/team.js"></script>
    <script>
        $(document).ready(function () {
            $('#notifBellBtn').click(function () {
                $.ajax({
                    url: '@Url.Action("Index", "Notification")',
                    success: function (result) {
                        $('#notificationModal .modal-content').html(result);
                        $('#notificationModal').modal('show');
                    }
                });
            });
        });
    </script>
}

ASI.Basecode.WebApp/Views/Team/_AddAgentModal.cshtml
@model ASI.Basecode.Services.ServiceModels.TeamViewModel

<div class="modal fade" id="addAgentModal" tabindex="-1" role="dialog" aria-labelledby="addAgentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addAgentModalLabel">Add Unassigned Agent</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addAgentForm">
                    <input type="hidden" id="TeamId" name="TeamId" value="@Model.TeamId" />
                    <div class="form-group">
                        <label for="AgentId">Select Agent</label>
                        <select class="form-control" id="AgentId" name="AgentId">
                            <option value="">-- Add Agent --</option>
                            @foreach (var agent in ViewBag.UnassignedAgents)
                            {
                                <option value="@agent.UserId">@agent.Name - @agent.Email</option>
                            }
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="submitAddAgent()">Add Agent</button>
            </div>
        </div>
    </div>
</div>

ASI.Basecode.WebApp/Views/Team/_ReassignAgentModal.cshtml
@model ASI.Basecode.Services.ServiceModels.TeamViewModel
@using ASI.Basecode.Data.Models;

@{
    var teams = ViewBag.Teams as List<Team>;
}

<div class="modal fade" id="reassignAgentModal" tabindex="-1" role="dialog" aria-labelledby="reassignAgentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="reassignAgentModalLabel">Reassign Agent</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="reassignAgentForm" method="post" asp-controller="Team" asp-action="ReassignAgent">
                    <input type="hidden" id="oldTeamId" name="oldTeamId" value="" />
                    <input type="hidden" id="agentId" name="agentId" value="" />
                    <div class="form-group">
                        <label for="newTeamId" class="control-label">Select New Team</label>
                        <select id="newTeamId" name="newTeamId" class="form-control">
                            <option value="">-- Unassign --</option>
                            @foreach (var teamGroup in teams.OrderBy(t => t.Specialization.CategoryName).GroupBy(t => t.Specialization.CategoryName))
                            {
                                <optgroup label="@teamGroup.Key">
                                    @foreach(var team in teamGroup)
                                    {
                                        <option value="@team.TeamId">@team.Name</option>
                                    }
                                </optgroup>
                            }
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="submitReassignAgent()">Reassign</button>
            </div>
        </div>
    </div>
</div>